### ISSUE TITLE
Process multiple sheets at once

### ISSUE THREAD

**Issue by MikeKutz** [mbleron/ExcelTable#1]
Some of the Excel files I had to process contained so much data that it was spread across multiple sheets.

It would be nice to have an option to say that the value for `p_sheet` was actually a Regular Expression for the Sheet name.

At the same time, the `FOR METADATA ()` syntax should support `SHEET_NAME` and `SHEET_INDEX`.

MK

**Comment by mbleron** [comment]
Yes, good idea, though it implies some substantial rework of the internals...
Adding it to the TODO list.

**Comment by mbleron** [comment]
Implemented in v3.0
