### ISSUE TITLE
ORA-04088: error during execution of trigger 'APPLDBA_P.BEFORE_GRANT_PUBLIC'

### ISSUE THREAD

**Issue by Urbik81** [mbleron/ExcelTable#16]
Hello, we used exceltable package a few week ago and everything was fine. During this period, our oracle admins applied some patch or etc. and now we get an oracle error ORA-04088 which is connected with trigger checking grants to PUBLIC.  I don't know why something should grant privileges to PUBLIC, but it seems that error emerges on this row - "open l_rc for l_query using p_file, p_method, p_password;" in first getCursor function in EXCELTABLE package. We use ORACLE DB 12.2. Do you have any idea where is granting privileges used and why emerges this error? Thank you in advance.

1) This is part of our SQL code:
declare
piv_excel_name ext_ds_upt_kalendar_pro_kl.nazev_souboru%TYPE := 'Kalendar.xlsx';
piv_nazev_listu ext_ds_upt_kalendar_pro_kl.nazev_listu%TYPE := 'Plan';
cv_db_adresar        CONSTANT VARCHAR2(16)   := 'DB_DIR';
lvr_data             SYS_REFCURSOR;

begin
     lvr_data :=
          ExcelTable.getCursor(
            p_file  => ExcelTable.getFile(cv_db_adresar, piv_excel_name)
          , p_sheet => piv_nazev_listu
          , p_cols  => '"A2" VARCHAR2(100) column ''A'''
          , p_range => 'A2:A2'            
          ); 
end;

2) This is whole error message:
Error report -
ORA-04088: error during execution of trigger 'APPLDBA_P.BEFORE_GRANT_PUBLIC'
ORA-00604: error occurred at recursive SQL level 3
ORA-20997: Public grants on data schema objects not allowed
ORA-06512: on line 23
ORA-06512: on "EXT_STAGE.EXCELTABLE", line 4087
ORA-06512: on line 11
04088. 00000 -  "error during execution of trigger '%s.%s'"
*Cause:    A runtime error occurred during execution of a trigger.
*Action:   Check the triggers which were involved in the operation.

3) This is the trigger mentioned above:
create or replace TRIGGER appldba_p.before_grant_public BEFORE GRANT ON DATABASE
declare
  vLst ora_name_list_t;
  vCnt int;

  function is_authorized(p_owner varchar2,p_grantor varchar2) return varchar2 is
    vRet varchar2(1);
  begin
    select decode(max(profile),'DAT_USER_PROFILE','F','T') into vRet from dba_users where username=p_owner;
    if vRet='F' then
      select decode(count(*),0,'F','T') into vRet from dba_role_privs where granted_role='DBA' and grantee=p_grantor;
    end if;
    return vRet;
  end;

begin
  if ora_dict_obj_name is null then
    return;
  end if;

  vCnt:=ora_grantee(vLst);
  for i in 1..nvl(vCnt,0) loop
    if vLst(i)='PUBLIC' and is_authorized(ora_dict_obj_owner,ora_login_user)='F' then
      raise_application_error(-20997,'Public grants on data schema objects not allowed');
    end if;
  end loop;
end;

**Comment by mbleron** [comment]
ExcelTable implements ODCI routines to return a dynamic dataset at runtime.
In the process, Oracle creates two system-generated objects to backup that dataset, an object type and its corresponding collection.
For some reasons, Oracle also issues GRANT TO PUBLIC command on them.
You can see that using a SQL trace, or by using `ora_sql_text()` in the trigger : 
```
GRANT EXECUTE ON "DEV"."SYSTPKcdXgynrRb6bPxwB3J7rog==" TO PUBLIC
GRANT EXECUTE ON "DEV"."SYSTPmBMFvp4dRoK+XjTAsQHMcQ==" TO PUBLIC
```
("DEV" is the owner of ExcelTable in my case)

Unfortunately, I have no idea yet why Oracle does that, and to what purpose.

**Comment by Urbik81** [comment]
Thank you for the analysis. Our db admin temporarily disabled the trigger. We will see if Oracle solve this bug.

**Comment by mbleron** [comment]
Closing this one, as not directly related to ExcelTable.
