### ISSUE TITLE
Error ORA-20722: Error at position 1 : unexpected symbol '<eof>' instead of '<identifier>'

### ISSUE THREAD

**Issue by arintaphon** [mbleron/ExcelTable#2]
When I run a script to test demo files, it shows the error

ORA-20722: Error at position 1 : unexpected symbol '<eof>' instead of '<identifier>'

Then show error message ORA-06512 of EXCELTABLE at line 704. 1077, 1090, 1219, 1230, 1242, 2217. And EXCELTABLEIMPL at line 16

Can you suggest me how to fix this issue?

Arintaphon

**Comment by mbleron** [comment]
I can't debug what I can't see.
Please post the exact SQL you've tried, and the database version.
Thanks.

**Comment by mbleron** [comment]
Closing this.
