### ISSUE TITLE
Pedro

### ISSUE THREAD

**Issue by prsalamancac** [mbleron/ExcelTable#20]
I have a problem. When i execute the sentence select, i don't received records. Say '0 records return'. What hapen? i don't found other messages. Thank.

**Comment by mbleron** [comment]
You're gonna have to tell me a lot more than that.
What SQL are you running?
Which file?
What's your database version?

Thanks.

**Comment by prsalamancac** [comment]
Good morning Marc. Thank you for your interest.

  *   The operating system is Windows 10 64 bits.

  *   The database is Oracle 18.c

  *   The file is Excel 2013, which has 100 rows (The file is atached)

The query is
select t.*
from table (
           ExcelTable.getRows(
            ExcelTable.getFile('TMP_DIR','PRMAT50M.xlsx'),
            'DataSource' ,
            ' "ID_IES" number , "ANNO" NUMBER , "SEMESTRE" number , "PRO_CONSECUTIVO"  number ,
              "ID_PARTICIPANTE"  number ,  "ID_TIPO_DOCUMENTO"  varchar2(6), "NUM_DOCUMENTO"  number ,
              "CODIGO_ESTUDIANTE"  varchar2(20) , "NUM_MAT_INSCRITAS"  number ,
              "VALOR_DERE_MAT"  number , "FUENTE"  varchar2(20)
             ' ,
             'A2'
          )
        ) t
   ;

When i execute with Sql Developer, it return (0 records return),


[cid:d6a3ce41-6602-4dac-8858-b065f66c3ae3]



Thank



De: Marc Bleron <notifications@github.com>
Enviado: sábado, 4 de abril de 2020 7:24 a. m.
Para: mbleron/ExcelTable <ExcelTable@noreply.github.com>
Cc: prsalamancac <prsalamancac@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [mbleron/ExcelTable] Pedro (#20)


You're gonna have to tell me a lot more than that.
What SQL are you running?
Which file?
What's your database version?

Thanks.

**Comment by mbleron** [comment]
Thanks for that, but your email attachment was lost.
Could you attach the file directly here on Github, in a comment?

**Comment by prsalamancac** [comment]
Thanks. Ok.
[PRMAT50M.xlsx](https://github.com/mbleron/ExcelTable/files/4432430/PRMAT50M.xlsx)

**Comment by mbleron** [comment]
You're using the wrong sheet name.
Should be 'Hoja1' : 

```
select t.*
from table (
       ExcelTable.getRows(
         ExcelTable.getFile('TMP_DIR','PRMAT50M.xlsx'),
        'Hoja1',
        '"ID_IES" number , "ANNO" NUMBER , "SEMESTRE" number , "PRO_CONSECUTIVO"  number ,
          "ID_PARTICIPANTE"  number ,  "ID_TIPO_DOCUMENTO"  varchar2(6), "NUM_DOCUMENTO"  number ,
          "CODIGO_ESTUDIANTE"  varchar2(20) , "NUM_MAT_INSCRITAS"  number ,
          "VALOR_DERE_MAT"  number , "FUENTE"  varchar2(20)
         ',
         'A2'
       )
     ) t
;
```

**Comment by prsalamancac** [comment]
Marc thank.

Excuseme for this mistake.

bye
Pedro

________________________________
De: Marc Bleron <notifications@github.com>
Enviado: sábado, 4 de abril de 2020 8:39 p. m.
Para: mbleron/ExcelTable <ExcelTable@noreply.github.com>
Cc: prsalamancac <prsalamancac@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [mbleron/ExcelTable] Pedro (#20)


You're using the wrong sheet name.
Should be 'Hoja1' :

select t.*
from table (
       ExcelTable.getRows(
         ExcelTable.getFile('TMP_DIR','PRMAT50M.xlsx'),
        'Hoja1',
        '"ID_IES" number , "ANNO" NUMBER , "SEMESTRE" number , "PRO_CONSECUTIVO"  number ,
          "ID_PARTICIPANTE"  number ,  "ID_TIPO_DOCUMENTO"  varchar2(6), "NUM_DOCUMENTO"  number ,
          "CODIGO_ESTUDIANTE"  varchar2(20) , "NUM_MAT_INSCRITAS"  number ,
          "VALOR_DERE_MAT"  number , "FUENTE"  varchar2(20)
         ',
         'A2'
       )
     ) t
;
