### ISSUE TITLE
Running getRows gives ORA-03113: end-of-file on communication channel error

### ISSUE THREAD

**Issue by aragorniiit** [mbleron/ExcelTable#24]
Hi

I uploaded sample_3.xlsx into a table xx_temp_files and ran below query in TOAD SQL editor.

SELECT x.*
  FROM xx_temp_files t,
       TABLE (ExcelTable.getRows (t.blob_content,
                                  'DataSource',
                                  ' "SRNO"    number
         , "NAME"    varchar2(10)
         , "VAL"     number
         , "DT"      date
         , "SPARE1"  varchar2(6)
         , "SPARE2"  varchar2(6)',
                                  'A2')) x
 WHERE t.id = 10154484

It results in below error. My database version is Oracle Database 11g Enterprise Edition Release 11.2.0.4.0. Please advise.

ORA-03113: end-of-file on communication channel
Process ID: 23816
Session ID: 213 Serial number: 13

Thanks
Kishore

**Comment by mbleron** [comment]
I'll try to reproduce the issue.

**Comment by aragorniiit** [comment]
Our java version is 1.8, do we run install_jdk6.sh to complete java installation step?

-bash-4.2$ java -version
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

**Comment by aragorniiit** [comment]
Running install_jdk6.sh gives exiting: Failures occurred during processing error.

**Comment by mbleron** [comment]
> Our java version is 1.8, do we run install_jdk6.sh to complete java installation step?

The mention 'jdk6' refers to the database-side JVM version, not your client's.
Oracle 11.2.0.4 comes with Java version 1.6, so yes, you can run install_jdk6.
But you only need Java-based features if you want to read large files or encrypted ODF 1.0/1.1 files. It's explained in the README.

**Comment by mbleron** [comment]
> Running install_jdk6.sh gives exiting: Failures occurred during processing error.

What does the log file say?

**Comment by mbleron** [comment]
Issue reproduced on 11.2.0.4.
Looks like ExcelTable v5 doesn't work anymore on that version, got Oracle internal error : 
`ORA-07445: core dump [qerocTabFuncPrepare()+5209] [ACCESS_VIOLATION] [ADDR:0x1C] [PC:0x3B8FB3B] [UNABLE_TO_READ] []`

I'll try to see what could be causing this but don't expect too much.

**Comment by aragorniiit** [comment]
I’m looking for a solution to parse excel macro file, apex_data_parser is
unable to do it.

Does older version of ExcelTable work on 11.2.0.4?

**Comment by mbleron** [comment]
I think it's due to `ODCITablePrepare` overloads in object type `ExcelTableImpl`. Strange I didn't see the problem sooner.
Those overloads are necessary for multisheet and flat files features, but somehow Oracle is messing with them at runtime.

The workaround in v5 is to disable (comment) all overloads but one.
For example : 
- if you require the ability to select only a single sheet _or_ multiple sheets using a regular expression, keep overload 1.
- if you require the ability to select multiple sheets using a static list (ExcelTableSheetList), keep overload 2.

Let me know if it is OK for you.
That's all I can come up with right now.

**Comment by aragorniiit** [comment]
Thanks for the prompt reply. I commented second overloaded ODCITablePrepare in ExcelTableImpl and it is working as expected. I'm able to parse excel macro file.

**Comment by aragorniiit** [comment]
My excel macro file can have more than default size 100 rows. I'm able to see all rows with getRows. Do I still need to call setFetchSize procedure?

**Comment by mbleron** [comment]
No, you don't have to call setFetchSize, you may leave the default value as is.
It's just a little optimization feature useful when Oracle requests large amount of rows from the table function, for example in a CREATE TABLE AS SELECT operation.
The default value will do fine in most cases.
