### ISSUE TITLE
Unknown sheet name

### ISSUE THREAD

**Issue by meskiocak** [mbleron/ExcelTable#25]
Hi,

In this example we have to write sheet name. 
SELECT t.*
  FROM TABLE (exceltable.getrows ( (SELECT l.file_data
                                      FROM apps.fnd_lobs l
                                     WHERE file_id = 505202),
                                  'data',
                                  ' "COL1"  number
                 , "COL2"  varchar2(100)
                 , "COL3"  number
                 , "COL4"  date
                 , "COL5"  varchar2(100)
                 , "COL6"  varchar2(100)
                 , "COL7"  varchar2(100)
                 ')) t
 WHERE col1 = '7'

What are we doing if we don't know the page name? Can we dynamically fetch the page name?

Best regards.

**Comment by meskiocak** [comment]
I found it.

SELECT *
  FROM TABLE (exceltable.getsheets ( (SELECT l.file_data
                                        FROM apps.fnd_lobs l
                                       WHERE file_id = 505202)))
 WHERE ROWNUM = 1

**Comment by mbleron** [comment]
Hi,
> What are we doing if we don't know the page name? Can we dynamically fetch the page name?

If there's only one sheet, just use a wildcard expression, e.g. '.*' (see [getRows](https://github.com/mbleron/ExcelTable#getrows-function) documentation).

**Comment by mbleron** [comment]
Closing the issue
