### ISSUE TITLE
Empty cells being skipped

### ISSUE THREAD

**Issue by Chris-Faceless-Avatar** [mbleron/ExcelTable#29]
Hi Marc,

I've been using your ExcelTable for a little while now.  Calling getRawCells on an XLS file, the empty cells aren't returning any value.  It's like they're getting skipped over.  Do you have pointers for this scenario.

Thank you,

Chris

**Comment by mbleron** [comment]
Hi Chris,

Yes, cell records of type [`Blank`](https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-xls/2918f1db-545e-432a-8f57-599c44251f07), [`MulBlank`](https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-xls/a9ab7fa1-183a-487c-a506-6b4a19e770be) or missing cell records are not retrieved via getRawCells.
Could you share a sample file so that I can check the internal types of those cells you're talking about?
Thanks.

**Comment by Chris-Faceless-Avatar** [comment]
Hi Marc,

Thanks for the quick reply.  I've done some data scrubbing, hoping that didn't alter the middle of the sheet that are blank.

 (edit)  Bit of background...  Using getRawCells to capture the column titles for a data mapping process downstream.  Iterating through columns that have a title but no accompanying value from the cursor calling getRawCells.
Chris

**Comment by mbleron** [comment]
Chris,

In your sample file, cells in columns L through U (except P) are missing in the source file, so  getRawCells does not report them.
On the contrary, cells in column P do exist and point to an empty string, so getRawCells reports a null VARCHAR2 value in the result set.

If you need to get columns having no data (except header), you can do something like this : 
```sql
with tmp as (
  select t.cellrow
       , t.cellcol
       , case when t.celldata.gettypename() = 'SYS.VARCHAR2' then t.celldata.accessvarchar2() end as string_value
       , case when t.celldata.gettypename() = 'SYS.NUMBER' then t.celldata.accessnumber() end as number_value
  from table(
         exceltable.getRawCells(
           exceltable.getFile('TEST_DIR','ExcelTable.sample.of.empty.cells.xls')
         , anydata.ConvertVarchar2('Issued Bonds')
         , 'A-AG'
         )
       ) t
)
select cellcol as column_ref
     , min(case when cellrow = 1 then string_value end) as column_title
from tmp
where ( string_value is not null or number_value is not null )
group by cellcol
having count(*) = 1
order by cellcol
;
 
COLUMN_REF COLUMN_TITLE
---------- -------------------------------------
L          License Number
M          Business Type
N          Business Name
O          DBA
P          Federal Taxpayer ID # (FEIN)
Q          Business Phone
R          Address
S          City
T          State
U          Zip

```

**Comment by mbleron** [comment]
Closing this one.
