### ISSUE TITLE
ExcelTable: getSheets function

### ISSUE THREAD

**Issue by ralmendares** [mbleron/ExcelTable#31]
First of all, thank you very much for such an excellent package. Sorry but I am something new to PLSQL. The truth is that I have not been able to figure out how I should use the **getSheets** function and I wanted to ask you for a code example of how I should use it. Maybe you could give me an example of code to use with one of the files that comes as an example (multisheet.xlsx for example). Thank you again

**Comment by mbleron** [comment]
Hi,

`getSheets` is a pipelined table function, so you have to use it from a SQL query if you want to embed it in PL/SQL code.

```
SQL> select column_value
  2  from table(
  3         ExcelTable.getSheets(
  4           ExcelTable.getFile('XL_DATA_DIR','multisheet.xlsx')
  5         )
  6       )
  7  ;
 
COLUMN_VALUE
------------------
Sheet2
Sheet1
Sheet3
 
```
From PL/SQL code, via an implicit cursor : 
```
SQL> declare
  2    sheetList  ExcelTableSheetList;
  3  begin
  4    select column_value
  5    bulk collect into sheetList
  6    from table(ExcelTable.getSheets(ExcelTable.getFile('XL_DATA_DIR','multisheet.xlsx')));
  7  
  8    for i in 1 .. sheetList.count loop
  9      dbms_output.put_line(sheetList(i));
 10    end loop;
 11  
 12  end;
 13  /
 
Sheet2
Sheet1
Sheet3
 
PL/SQL procedure successfully completed.
 
```

**Comment by ralmendares** [comment]
Thank you very much Marc, very kind of you to take the time to answer me,
excellent package

**Comment by mbleron** [comment]
You're welcome.
