### ISSUE TITLE
Using Table function in PL/SQL

### ISSUE THREAD

**Issue by omarsawalhah** [mbleron/ExcelTable#37]
I tried to use the following select in a procedure but I got

select /*+ cursor_sharing_exact */ t."Schema" schema,t."Table Name" table_name,t."Partition Name" partition_name,
       t."Partition High Value Date" high_value_date,
       t."Tablespace Name" tablespace_name,
       t."Retention" retention
    from table(
           ExcelTable.getRows(
             ExcelTable.getFile('EXCELFILES','s1.xlsx')
           , 'To_be_archived'
           , ' "Schema"                         varchar2(30)
             , "Table Name"                     varchar2(30)
             , "Partition Name"                 varchar2(30)
             , "Partition High Value Date"      date
            , "Tablespace Name"                 varchar2(30)
            , "Retention"                       varchar2(30)'
          , 'A8'
          )
        ) t;
Error(40,10): PL/SQL: ORA-22905: cannot access rows from a non-nested table item

**Comment by mbleron** [comment]
That's only supported starting from Oracle 18c, unfortunately.
See this blog post I wrote about this issue, including workarounds for versions < 18 : 
[Oracle 18c : PL/SQL support for pipelined table functions returning ANYDATASET](https://odieweblog.wordpress.com/2019/05/14/oracle-18c-pl-sql-support-for-pipelined-table-functions-returning-anydataset/)
