### ISSUE TITLE
install script reference missing MSUtility

### ISSUE THREAD

**Issue by adrianboangiu** [mbleron/ExcelTable#39]
Hello,
The new MSUtility does not contain anymore CDFReader and thus the installation script fails.
Previously MSUtilities was different in ExcelGen and ExcelTable (one contained CDFReader the other CDFManager). Now, there is only one MSUtilities and it contains only CDFmanager.

Best regards

**Comment by mbleron** [comment]
Sorry for that. I know I should have tested more before commiting.

**Comment by mbleron** [comment]
Installation script updated
