### ISSUE TITLE
package xutl_offcrypto created with compilation errors

### ISSUE THREAD

**Issue by adrianboangiu** [mbleron/ExcelTable#40]
Hello,

I got the following errors for the package xutl_offcrypto:

Avertissement : Corps de package crÚÚ avec erreurs de compilation.

SQL> show error
Erreurs pour PACKAGE BODY XUTL_OFFCRYPTO :

LINE/COL ERROR
-------- -----------------------------------------------------------------
1391/5   PL/SQL: Statement ignored
1391/21  PLS-00302: Le composant 'NEW_FILE' doit Ûtre dÚclarÚ
1393/5   PL/SQL: Statement ignored
1393/14  PLS-00302: Le composant 'ADD_STREAM' doit Ûtre dÚclarÚ
1394/5   PL/SQL: Statement ignored
1394/14  PLS-00302: Le composant 'ADD_STREAM' doit Ûtre dÚclarÚ
1395/5   PL/SQL: Statement ignored
1395/14  PLS-00302: Le composant 'ADD_STREAM' doit Ûtre dÚclarÚ
1396/5   PL/SQL: Statement ignored
1396/14  PLS-00302: Le composant 'ADD_STREAM' doit Ûtre dÚclarÚ
1398/5   PL/SQL: Statement ignored

LINE/COL ERROR
-------- -----------------------------------------------------------------
1398/14  PLS-00302: Le composant 'ADD_STREAM' doit Ûtre dÚclarÚ
1399/5   PL/SQL: Statement ignored
1399/14  PLS-00302: Le composant 'ADD_STREAM' doit Ûtre dÚclarÚ
1400/5   PL/SQL: Statement ignored
1400/24  PLS-00302: Le composant 'GET_FILE' doit Ûtre dÚclarÚ

Best regards,

**Comment by mbleron** [comment]
Those are dependencies from XUTL_CDF package. 
Is it installed correctly? Maybe a side effect of issue #39?

**Comment by adrianboangiu** [comment]
I confirm that the fix for #39 fixed also this one.
