### ISSUE TITLE
DML API insert static values from PLSQL

### ISSUE THREAD

**Issue by jordancortes** [mbleron/ExcelTable#6]
Is there a way to include static values coming from PLSQL variables as part of the new DML API INSERT operation?

For example

    DECLARE
        ctx         ExcelTable.DMLContext;
        nrows       INTEGER;
        user_email  VARCHAR2(100);
    BEGIN
        -- Set variables
        ctx := ExcelTable.createDMLContext('TMP_SAMPLE2');
        user_email := 'myEmail@provider.com';
    
        ExcelTable.mapColumn(ctx, p_col_name => 'NAME',         p_col_ref => 'B');
        ExcelTable.mapColumn(ctx, p_col_name => 'VAL',          p_col_ref => 'C');
        ExcelTable.mapColumn(ctx, p_col_name => 'CREATED_BY',   /* a way to referece variable user_email*/);
    
        nrows := ExcelTable.loadData(
            p_ctx      => ctx
            , p_file     => ExcelTable.getFile('XL_DATA_DIR','sample_2.xlsx')
            , p_sheet    => 'DataSource'
            , p_dml_type => ExcelTable.DML_INSERT
        );
    END;
    /

**Comment by mbleron** [comment]
It's currently not possible, but I'll consider it for a future release.

Thanks.

**Comment by mbleron** [comment]
Implemented in v3.1
