### ISSUE TITLE
ORA-29532: Java call terminated by uncaught Java exception: 

### ISSUE THREAD

**Issue by michalfichtner** [mbleron/ExcelTable#8]
Hello, we are able to load small file,
 in case we would like to use big file with this code 

`select * 
from table(
       ExcelTable.getRows(
         ExcelTable.getFile('BI','bigfile.xlsx')
       , 'data'      
       , q'{ 
            "ID"           number
          , "FIRST_NAME"   varchar2(15)
          , "LAST_NAME"    varchar2(20)
          , "EMAIL"        varchar2(30)
          , "GENDER"       varchar2(10)
          , "IP_ADDRESS"   varchar2(16)
          , "COMMENT"      varchar2(4000)
          , "IMAGE"        varchar2(4000)
          , "DT"           date  format 'DD/MM/YYYY'
         }'
       , 'A2'
       , 1
       )
     ) t ;` 

we have this issue 

`ORA-29532: Java call terminated by uncaught Java exception: javax.xml.stream.FactoryConfigurationError: java.security.AccessControlException: the Permission (java.lang.RuntimePermission getClassLoader) has not been granted to BI. The PL/SQL to grant this is dbms_java.grant_permission( 'BI', 'SYS:java.lang.RuntimePermission', 'getClassLoader', '' )
ORA-06512: at "BI.EXCELTABLE", line 1443
ORA-06512: at "BI.EXCELTABLE", line 1971
ORA-06512: at "BI.EXCELTABLE", line 2146
ORA-06512: at "BI.EXCELTABLE", line 2649
ORA-06512: at "BI.EXCELTABLEIMPL", line 60
ORA-06512: at line 1
29532. 00000 -  "Java call terminated by uncaught Java exception: %s"
*Cause:    A Java exception or error was signaled and could not be
           resolved by the Java code.
*Action:   Modify Java code, if this behavior is not intended.`

can you please look on it and help us? 
We are using oracle 12c

thank you

**Comment by mbleron** [comment]
Have you tried running the DBMS_JAVA call suggested in the error message?
Should solve the issue.

`dbms_java.grant_permission( 'BI', 'SYS:java.lang.RuntimePermission', 'getClassLoader', '' )`

**Comment by michalfichtner** [comment]
Yes we do it but it is still same. :(

**Comment by michalfichtner** [comment]
Solved by update of oracle cluster DB

**Comment by trsiqueir** [comment]
What kind of update you did? Was it on the weblogic cluster or on the database?
